//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarangGodhariM17_Lab3_Ex1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarangTB
    {
        public int learnerID { get; set; }
        public string learnerName { get; set; }
        public string currentMajor { get; set; }
        public string strongestSkill { get; set; }
        public string favouriteSubject { get; set; }
    }
}
